MVC Eticaret/Controllers/SifreController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Eticaret.Models;
using System.Linq;

namespace MVC_Eticaret.Controllers
{
    public class SifreController : Controller
    {
   // GET: Sifre

        public ActionResult ResetPassword(string id)
        {
            string sfr = "";

            foreach (char x in id)
            {
                int ascii = (int)x - 3;
                sfr += (char)ascii;
            }
            if (string.IsNullOrWhiteSpace(id))
            {
                return RedirectToAction("Eror404");

            }

            using (var context = new Context())
            {
                var user = context.UserProfile.Where(a => a.Mail == sfr).FirstOrDefault();
                if (user != null)
                {
                    ResetPasswordModel model = new ResetPasswordModel();
                    model.ResetCode = id;
                    return View(model);
                }


                else
                {
                    return RedirectToAction("Eror404");
                }
            }
        }

        [HttpPost]
        public ActionResult ResetPassword(ResetPasswordModel model)
        {
            string sfr = "";
            foreach (char x in model.ResetCode)
            {
                int ascii = (int)x - 3;
                sfr += (char)ascii;
            }

            var message = "";
            if (ModelState.IsValid)
            {
                using (var context = new Context())
                {
                    var user = context.UserProfile.Where(a => a.Mail == sfr).FirstOrDefault();
                    if (user != null)
                    {
                        user.Password = model.NewPassword;
                        context.SaveChanges();
                        message = "Yeni Şifre Güncellendi";
                    }

                }
            }
            else
            {
                message = "Bir Şeyler Yanlış Gitti";
            }
            ViewBag.Message = message;
            return View();
        }
    }
}

MVC Eticaret/Views/Sifre/ResetPassword.cshtml
@model MVC_Eticaret.Models.ResetPasswordModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="/Content/js/examples/renk-degistir.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Şifreyi Yenile</title>
</head>
<body>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <style>

        .forget-pwd > a {
            color: #dc3545;
            font-weight: 500;
        }

        .forget-password .panel-default {
            padding: 31%;
            margin-top: -22%;
        }

        .forget-password .panel-body {
            padding: 15%;
            margin-bottom: -50%;
            background: #fff;
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        }

        img {
            width: 40%;
            margin-bottom: 10%;
        }

        .btnForget {
            background: #c0392b;
            border: none;
        }

        .forget-password .dropdown {
            width: 100%;
            border: 1px solid #ced4da;
            border-radius: .25rem;
        }

            .forget-password .dropdown button {
                width: 100%;
            }

            .forget-password .dropdown ul {
                width: 100%;
            }
    </style>
    <div class="container forget-password " style="height: 100vh;">
        <div class="align-self-center " style="height: 100vh;">

            @using (Html.BeginForm("ResetPassword","Sifre", FormMethod.Post))
            {
                <div class="row">
                    <div class="col-md-12 col-md-offset-4 ">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="text-center">
                                    <img src="https://i.ibb.co/rshckyB/car-key.png" alt="car-key" border="0">
                                    <p>Şifrenizi Sıfırlayabilirsiniz.</p>
                                    <div class="text-danger">
                                        @ViewBag.Message
                                        @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                                        @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    </div>
                                    <form id="register-form" role="form" autocomplete="off" class="form" method="post">
                                        <div class="form-group">
                                            <div class="input-group">
                                                <input type="text" name="NewPassword" id="NewPassword" placeholder="Yeni Şifre " class="form-control" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="input-group">
                                                <input type="text" name="ConfirmPassword" id="ConfirmPassword" placeholder="Şifreyi onayla " class="form-control" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.HiddenFor(a => a.ResetCode)
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" value="Kaydet" class="btn btn-primary mt-2 btn-block" />
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>


</body>
</html>